server:
  port: 8888
  
spring:  cloud:    config:      server:        git:          uri: https://github.com/abelfgdeveloper/common-back-config-repository
          clone-on-start: true
          search-paths:          
          
logging:
  level:
    root: warn
    '[es.abelfgdeveloper]': info